added CartServiceImplTest
Estrin-MBicycle/storify-app pull request #105
Opened 2022-03-04 11:25 UTC by aliaksharbachou

2022-03-07 11:25 UTC, Estrin-MBicycle requested changes

2022-03-07 11:25 UTC, Estrin-MBicycle commented on src/test/java/internship/mbicycle/storify/unit/CartServiceImplTest.java
> +    private static Authentication auth;
why do we need global variable?

2022-03-09 10:20 UTC, aliaksharbachou commented on src/test/java/internship/mbicycle/storify/unit/CartServiceImplTest.java
> +    private static Authentication auth;
I changed

2022-03-09 14:21 UTC, andrey11m commented on src/test/java/internship/mbicycle/storify/unit/CartServiceImplTest.java
> +    void testFindByCart() {
Why the name is "findByCart"?

2022-03-09 14:21 UTC, andrey11m commented on src/test/java/internship/mbicycle/storify/unit/CartServiceImplTest.java
> +        StorifyUser storifyUser = new StorifyUser();
Why you didn't use builder?

2022-03-10 09:28 UTC, aliaksharbachou commented on src/test/java/internship/mbicycle/storify/unit/CartServiceImplTest.java
> +    void testFindByCart() {
changed

2022-03-10 09:30 UTC, aliaksharbachou commented on src/test/java/internship/mbicycle/storify/unit/CartServiceImplTest.java
> +        StorifyUser storifyUser = new StorifyUser();
because the builder is not suitable here

2022-03-10 09:43 UTC, merged