fixed bags with access to profile
Estrin-MBicycle/storify-app pull request #111
Opened 2022-03-09 12:17 UTC by andrey11m

2022-03-09 13:59 UTC, Estrin-MBicycle requested changes

2022-03-09 13:59 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/ProfileController.java
> +    @GetMapping("")
("") is redundant, use just @GetMapping

2022-03-09 13:59 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/ProfileController.java
> +    @PutMapping("")
("") is redundant

2022-03-10 08:29 UTC, mariyazaiceva commented on src/main/java/internship/mbicycle/storify/controller/ProfileController.java
> +    @GetMapping("")
Done

2022-03-10 08:29 UTC, mariyazaiceva commented on src/main/java/internship/mbicycle/storify/controller/ProfileController.java
> +    @PutMapping("")
Done

2022-03-10 09:36 UTC, merged