added method getAllPurchasesByProfile
Estrin-MBicycle/storify-app pull request #113
Opened 2022-03-09 13:43 UTC by aliaksharbachou

2022-03-09 13:53 UTC, Estrin-MBicycle requested changes

2022-03-09 13:53 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +        List<PurchaseDTO> f = purchaseService.getAllPurchasesByProfile(principal);
f? what the hell?)))

2022-03-09 13:53 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +        System.out.println(f);
why do we need it?))

2022-03-10 09:33 UTC, aliaksharbachou commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +        List<PurchaseDTO> f = purchaseService.getAllPurchasesByProfile(principal);
sorry, i forgot to change. done

2022-03-10 12:17 UTC, merged