added swagger
Estrin-MBicycle/storify-app pull request #2
Opened 2022-02-04 20:56 UTC by andrey11m

2022-02-06 07:59 UTC, Estrin-MBicycle requested changes

2022-02-06 07:59 UTC, Estrin-MBicycle commented on pom.xml
> +        <dependency>
I'm not sure you need this starter

2022-02-06 07:59 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/configurations/SwaggerConfig.java
> +package internship.mbicycle.storify.configurations;
Please rename pack from 'configurations' to 'configuration'

2022-02-06 10:19 UTC, andrey11m commented on pom.xml
> +        <dependency>
It didn't work for me without boot starter and i found that from 2.2 version spring boot need this depency

2022-02-06 10:22 UTC, andrey11m commented on src/main/java/internship/mbicycle/storify/configurations/SwaggerConfig.java
> +package internship.mbicycle.storify.configurations;
I took names of packs from timetracker, the name of controllers or configufations must be like controller and configufation?

2022-02-08 08:50 UTC, OlgaEvdokimova commented on src/main/java/internship/mbicycle/storify/configurations/SwaggerConfig.java
> +package internship.mbicycle.storify.configurations;
Yes, we name packeges in singular

2022-02-08 08:50 UTC, OlgaEvdokimova commented on src/main/resources/application.yml
> +      matching-strategy: ant_path_matcher
Are u going to use different content in your requests?

2022-02-08 08:50 UTC, OlgaEvdokimova commented on pom.xml
> +        <dependency>
Use 3.0 version

2022-02-08 08:58 UTC, OlgaEvdokimova commented on pom.xml
> +        <dependency>
Try to use only this one dependency https://mvnrepository.com/artifact/io.springfox/springfox-boot-starter

2022-02-08 14:32 UTC, andrey11m commented on src/main/resources/application.yml
> +      matching-strategy: ant_path_matcher
Just without it didn't work swagger for me

2022-02-09 09:48 UTC, closed without merging