added validation to storifyUser
Estrin-MBicycle/storify-app pull request #92
Opened 2022-02-23 14:04 UTC by andrey11m

2022-02-23 14:32 UTC, Estrin-MBicycle requested changes

2022-02-28 10:50 UTC, Estrin-MBicycle requested changes

2022-02-28 10:50 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/StorifyUserController.java
> +                            @PathVariable String code, Principal principal) {
Move principal to new line

2022-02-28 12:01 UTC, andrey11m commented on src/main/java/internship/mbicycle/storify/controller/StorifyUserController.java
> +                            @PathVariable String code, Principal principal) {
Done

2022-03-01 12:36 UTC, OlgaEvdokimova approved these changes

2022-03-01 12:36 UTC, merged