added CartService and CartController
Estrin-MBicycle/storify-app pull request #97
Opened 2022-02-28 09:55 UTC by aliaksharbachou

2022-02-28 10:21 UTC, Estrin-MBicycle requested changes

2022-02-28 10:21 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +    @DeleteMapping("/delete/{id}")
"/delete" part is redundant

2022-02-28 10:21 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +    @PutMapping("/deleteByCount/{id}/{count}")
"/deleteByCount" part is redundant

2022-02-28 10:21 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +    @DeleteMapping("/delete-all")
"/delete-all" is redundant

2022-02-28 10:21 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +    @PostMapping("/addProducts/{id}/{count}")
"/addProducts" is redundant

2022-02-28 10:21 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/converter/CartConverter.java
> +            sum += productDTO.getPrice() * entry.getValue();
try to use ObjectMapper instead

2022-02-28 10:21 UTC, Estrin-MBicycle commented on src/main/java/internship/mbicycle/storify/dto/ProductDetailInCartDTO.java
> +    private String product_name;
product_name? What the hell with naming?)

2022-03-02 07:21 UTC, OlgaEvdokimova requested changes

2022-03-02 07:21 UTC, OlgaEvdokimova commented on src/main/java/internship/mbicycle/storify/converter/CartConverter.java
> +            sum += productDTO.getPrice() * entry.getValue();
try to use stream api

2022-03-02 08:13 UTC, aliaksharbachou commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +    @DeleteMapping("/delete-all")
done

2022-03-02 08:13 UTC, aliaksharbachou commented on src/main/java/internship/mbicycle/storify/dto/ProductDetailInCartDTO.java
> +    private String product_name;
done

2022-03-02 08:15 UTC, aliaksharbachou commented on src/main/java/internship/mbicycle/storify/converter/CartConverter.java
> +            sum += productDTO.getPrice() * entry.getValue();
maybe there are examples of an object mapperwith a map?

2022-03-03 08:41 UTC, aliaksharbachou commented on src/main/java/internship/mbicycle/storify/converter/CartConverter.java
> +            sum += productDTO.getPrice() * entry.getValue();
done

2022-03-03 08:41 UTC, aliaksharbachou commented on src/main/java/internship/mbicycle/storify/controller/CartController.java
> +    @PutMapping("/deleteByCount/{id}/{count}")
done

2022-03-03 08:41 UTC, aliaksharbachou commented on src/main/java/internship/mbicycle/storify/converter/CartConverter.java
> +            sum += productDTO.getPrice() * entry.getValue();
done

2022-03-03 09:16 UTC, merged